惡魔十字 : [ Devil's Crossing ]
下游渡口 : [ Lower Crossing ]
殮葬山脈 : [ Burial Hill ]
舊垃圾場 : [ The Old Dump ]
迷霧河畔 : [ Foggy Bank ]
屍妖泥沼 : [ Wightmire ]
濕潤山谷 : [ Sodden Hollow ]
伯爾維治郊外 : [ Burrwitch Outskirts ]
腐壞田地 : [ Moldering Fields ]
泥濘道路 : [ Mud Row ]
伯爾維治村 : [ Burrwitch Village ]
典獄長的地下室 : [ The Warden's Cellar ]
地下通道 : [ Underground Transit ]
隱密實驗室 : [ Hidden Laboratory ]
廢棄庫房 : [ Abandoned Storerooms ]
地下監牢 : [ Underground Jail ]
廢棄宿舍 : [ Living Quarters ]
實驗室內部 : [ Inner Laboratory ]
 : [  ]
 : [  ]
 : [  ]
 : [  ]
 : [  ]
 : [  ]
 : [  ]
 : [  ]
 : [  ]
 : [  ]
 : [  ]
 : [  ]
 : [  ]
 : [  ]
 : [  ]
 : [  ]
 : [  ]
 : [  ]
 : [  ]
 : [  ]
 : [  ]
 : [  ]
